apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{app_name}}
  labels:
    app: {{app_label}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80