apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app_web_ideas_extraordinarias
  labels:
    app: web_ideas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_ideas
  template:
    metadata:
      labels:
        app: web_ideas
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
