apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web_name
  labels:
    app: web_label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web_label
  template:
    metadata:
      labels:
        app: web_label
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
